### ISSUE TITLE
Use Default API Level 19

### ISSUE THREAD

**Issue by FeralBytes** [cocodevienne/pique#1]
In Buildozer.spec set API Level = 19
Also without logcat you are dead in the water. Basic troubleshooting requires that you be able to see what is happening.

**Comment by cocodevienne** [comment]
Okay Ill give it a shot! Thanks!!! Sorry I only saw it now!:)

**Comment by cocodevienne** [comment]
@FeralBytes

**Comment by cocodevienne** [comment]
So as I told everyone in the previous issue on kivy/kivy, the USB port is broken on my phone. Is there anyway to take the logcat without my phone connected drectly? I tried API Lvl 19 btw and still keeps crashing. I also included the buildozer.spec in the source directory.

**Comment by cocodevienne** [comment]
@FeralBytes

**Comment by FeralBytes** [comment]
Unfortunately the only other option is the wifi based logcat; but as pointed out it will require root. Having no USB and doing android development is unfortunately not really compatable. Sorry. Without USB and Logcat as I said you are dead in the water.

**Comment by cocodevienne** [comment]
@FeralBytes I know it might be asking a bit much, but could you maybe install it on your device and tell me what the issue is? I would be infinitely grateful to you and the App is really just a very,very simple calculator. No virus, just a tool.

**Comment by FeralBytes** [comment]
OK I thought about it and I have another way that you can actually help yourself. You already have the android SDK and NDK, so just download and launch and Android Emulator. Then you can install the APK into the emulator and connect to it with logcat. Then you will be able to see and troubleshoot.

**Comment by cocodevienne** [comment]
How do I start the emulator and how do I tell buildozer to pull the logcat from that emulator? I'm sorry if this is a silly question but I'm still relatively new to all this!:) @FeralBytes

**Comment by FeralBytes** [comment]
What OS are you running on. You will have to find the Google Android SDK on your system. In a folder for it you will see a program file called simply "android" starting that will bring you to an interface that lists the currently download APIs. Under the tools menu is an option about "AVD". In there you can create a emulator.  Then you can start it.  
https://developer.android.com/studio/run/managing-avds.html

**Comment by cocodevienne** [comment]
@FeralBytes I'm runnig on Ubuntu Xenial Xerus 16.04 AMD 64. Now I instlled everything and found the android file and executed it. Then I realised that there was only a list of packages that I can install and I couldn't find the Emulator! Where is it?

**Comment by FeralBytes** [comment]
Make sure you have installed one of the emulator files:
![image](https://cloud.githubusercontent.com/assets/7874274/23309361/654f2a9e-fa7c-11e6-8e99-2c3cae565cc9.png)

Then you need to click "Tools > Manage AVDs" and this gui will appear.
![image](https://cloud.githubusercontent.com/assets/7874274/23309415/9844c814-fa7c-11e6-8c9a-f0590be2cfe0.png)

Then I recommend you choose the Device Definitions Tab and pick one; then choose "Create Device" button. Now you will have an Android Emulator and you can choose Start. 
ADB will automatically recognize and connect to the AVD device.

**Comment by cocodevienne** [comment]
Ok, thanks, will try this ASAP!:) Thank you very much!!

**Comment by cocodevienne** [comment]
@FeralBytes

**Comment by cocodevienne** [comment]
@FeralBytes It got fixed. The error was occurring because I imported the `Screen` and `Screenmanager` classes in the same `import` statement. After I fixed that, the compiled APK didn't crash! Thanks for all the help though! I appreciate it.
